package com.kazipay.identity.domain;

public enum Permission {
    CLIENT_READ, CLIENT_WRITE, PROJECT_READ, PROJECT_WRITE, TASK_WRITE, TIME_LOG, TIME_APPROVE,
    EXPENSE_APPROVE, INVOICE_READ, INVOICE_WRITE, INVOICE_SEND, INVOICE_VOID, PAYMENT_RECORD,
    PAYMENT_REFUND, REPORT_READ, TEAM_MANAGE, SETTINGS_MANAGE, GATEWAY_MANAGE, BILLING_MANAGE
}